version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      # login to Elastic container registry
      - eval $(aws ecr get-login --region us-west-2 --no-include-email | sed 's|https://||')
      - REPOSITORY_URI=763096341704.dkr.ecr.us-west-2.amazonaws.com/caheredia/caiso_connector
      - IMAGE_TAG=1.0
  build:
    commands:
      - echo Build started on `date`
      - echo Starting build commands
      - pip3 install --upgrade pip
      - pip3 install poetry==0.12.17
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push $REPOSITORY_URI:$IMAGE_TAG


