version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo Starting build commands
      - pip3 install --upgrade pip
      - pip3 install poetry==0.12.17
      - apt-get install -y sqlite3
  build:
    commands:
      - echo Build started on `date`
      - sqlite3 --version
  post_build:
    commands:
      - echo Build completed on `date`
      - poetry config settings.virtualenvs.create false
      - poetry install --no-dev

