version: "3"
services:
  web:
    image: caheredia/caiso-connector:8a02383ccd6905aa1ca2e617b5eef20b8375a361
    container_name: "caiso-connector"
    ports:
      - "80:80"
    volumes:
      - .:/code
    working_dir: /code
  demo:
    image: python:3.8.3-slim
    container_name: "demo_container"
    command: /bin/bash -c "tail -f /dev/null"
    entrypoint: ""
