version: "3"
services:
  web:
    image: caheredia/caiso-connector:f9ff28934d700a77c203edbf5496573ed1fc1560
    container_name: "caiso-connector"
    ports:
      - "80:80"
    volumes:
      - .:/code
    working_dir: /code
  demo:
    image: python:3.8.3-slim
    container_name: "demo_container"
    command: /bin/bash -c "tail -f /dev/null"
    entrypoint: ""
