version: "3"
services:
  rest_api:
    build: .
    container_name: "caiso_connector"
    ports:
      - "80:80"
  demo:
    image: python:3.8.3-slim
    container_name: "demo_container"
    command: /bin/bash -c "tail -f /dev/null"
    entrypoint: ""

