# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: caheredia/caiso-connector:99b487088cb76849dc84cebc7a5be047a0b3501d

    steps:
      - uses: actions/checkout@v2
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --max-complexity=10 --max-line-length=127 --show-source --statistics
      - name: Format with Black
        run: |
          black --check .
      - name: Check isort
        run: |
          isort --recursive --check-only --diff
      - name: Test with pytest
        run: |
          python -m pytest --cov=./ --cov-report=xml  tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests

